export const UPLOAD_FILE = 'UPLOAD_FILE'
export const UPLOAD_FILE_START = 'UPLOAD_FILE_START'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
